apiVersion: v1
kind: PersistentVolume
metadata:
  name: falkordb-pv
  labels:
    type: local
    app: lattice
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/lattice/falkordb
