apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: falkordb-pvc
  namespace: lattice
  labels:
    app: lattice
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
